title: "M³J"
remote_theme: pmarsceill/just-the-docs
color_scheme: blue
search_enabled: true

# allows links without .html extension
permalink: pretty

# Aux links for the upper right navigation
aux_links:
  "M³J on GitHub":
    - "//github.com/mmmjam"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2019-2021 Massachusetts Math Modeling Jam.</a>"

plugins:
  - jekyll-seo-tag